                                                                                                                                                                                                                                                        ?column?                                                                                                                                                                                                                                                         
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE public.Consumable (currentStock double precision, reorderPoint integer, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, maxStock integer, minStock integer, reorderQty integer, unitCost double precision, id text, name text, category text, unit text, description text, image text, location text, supplierId text);
 CREATE TABLE public.Proposal (targetDate timestamp without time zone, estimateApproved boolean, type USER-DEFINED, urgency USER-DEFINED, estimate double precision, status USER-DEFINED, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, quotesCount integer, id text, title text, vendor text, owner text, nextAction text, description text, estimateApprovedBy text, quotesPdfs ARRAY, supplierId text);
 CREATE TABLE public.User (role USER-DEFINED, cities ARRAY, isActive boolean, lastLogin timestamp without time zone, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, email text, password text, name text, refreshToken text);
 CREATE TABLE public.Area (isActive boolean, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, name text, description text);
 CREATE TABLE public.PurchaseOrderItem (createdAt timestamp without time zone, updatedAt timestamp without time zone, quantity double precision, receivedQty double precision, unitPrice double precision, totalPrice double precision, id text, purchaseOrderId text, consumableId text);
 CREATE TABLE public.EventBrief (briefStatus USER-DEFINED, riskLevel USER-DEFINED, city USER-DEFINED, date timestamp without time zone, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, artist text, genre text, setTimes text, stagePlotLink text, inputListLink text, monitorNeeds text, ljCueNotes text, vjContentChecklist text, timecodeRouting text, sfxNotes text, audioOrder text, brandMoment text, liveSetRecording text, specialLightingOrder text, visualOrder text);
 CREATE TABLE public.KPIMetrics (city USER-DEFINED, nightsOpen integer, equipmentUptimePercentage double precision, issuesRaised integer, issuesResolved integer, powerIncidents integer, weekYear integer, weekNumber integer, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text);
 CREATE TABLE public.Alert (type USER-DEFINED, timestamp timestamp without time zone, acknowledged boolean, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, title text, message text);
 CREATE TABLE public.PurchaseOrder (orderDate timestamp without time zone, expectedDate timestamp without time zone, receivedDate timestamp without time zone, status USER-DEFINED, totalAmount double precision, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, orderNumber text, supplierId text, notes text);
 CREATE TABLE public.MaintenanceLog (date timestamp without time zone, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, type USER-DEFINED, status USER-DEFINED, mttr double precision, cost double precision, id text, issue text, parts ARRAY, equipmentId text, notes text, technicianId text, photo text, supplierId text);
 CREATE TABLE public.RolePermission (role USER-DEFINED, granted boolean, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, permissionId text);
 CREATE TABLE public.Incident (type USER-DEFINED, date timestamp without time zone, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, description text, rootCause text, prevention text, impact text);
 CREATE TABLE public.CrewMember (shift USER-DEFINED, assigned boolean, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, name text, role text);
 CREATE TABLE public.StockMovement (type USER-DEFINED, quantity double precision, balanceBefore double precision, balanceAfter double precision, unitCost double precision, totalCost double precision, city USER-DEFINED, createdAt timestamp without time zone, id text, consumableId text, reference text, notes text, performedBy text);
 CREATE TABLE public.RndProject (phase USER-DEFINED, progress integer, budget double precision, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, actualCost double precision, actualLiveDate timestamp without time zone, milestones jsonb, status USER-DEFINED, targetDate timestamp without time zone, id text, title text, description text, risks ARRAY, dependencies ARRAY, lead text, notes text);
 CREATE TABLE public.Supplier (city USER-DEFINED, paymentTerms integer, rating double precision, status USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, name text, code text, contactPerson text, email text, phone text, address text, taxId text, notes text);
 CREATE TABLE public.PushSubscription (isActive boolean, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, userId text, endpoint text, p256dh text, auth text, userAgent text);
 CREATE TABLE public.Equipment (status USER-DEFINED, lastInspection timestamp without time zone, nextDue timestamp without time zone, city USER-DEFINED, createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, name text, firmware text, description text, photo text, areaId text);
 CREATE TABLE public.EquipmentInspection (date timestamp without time zone, createdAt timestamp without time zone, equipmentId text, inspector text, condition text, notes text, issues ARRAY, id text);
 CREATE TABLE public.Notification (type USER-DEFINED, category USER-DEFINED, data jsonb, city USER-DEFINED, read boolean, readAt timestamp without time zone, createdAt timestamp without time zone, id text, userId text, title text, message text, actionUrl text);
 CREATE TABLE public.Permission (createdAt timestamp without time zone, updatedAt timestamp without time zone, id text, name text, displayName text, description text, category text);
(21 rows)

